### ISSUE TITLE
posterior mean correlations among random intercepts and slopes

### ISSUE THREAD

**Issue by mitezo** [atrihub/ltjmm#1]
May I ask a beginner's question? Could you please instruct me on how to calculate the posterior mean correlations among random intercepts and slopes, as well as their 95% credible intervals, for the four outcomes in the vignettes' code?

**Comment by mcdonohue** [comment]
Here is some code based on the second section of the vignette to extract the correlation and covariance matrices for the random effects:

```{r}
fit <- ltjmm_stan(Y ~ year |
  1  | # fixed effects direct on outcome
  id | outcome,
 random_effects = "multivariate",
 data = dd,
 seed = rng_seed,
 chains = 2, parallel_chains = 2,
 iter_warmup = 500, iter_sampling = 500, thin = 2)
fit.sum <- fit$summary(c("beta", "gamma", "sigma_delta", "delta", 
  "alpha0", "alpha1", "Omega", "Sigma")) %>%
 as.data.frame()
row.names(fit.sum) <- fit.sum %>% pull(variable)
draws.beta <- fit$draws("beta")
draws.gamma <- fit$draws("gamma")
draws.sigma_delta <- fit$draws("sigma_delta")
draws.Omega <- fit$draws("Omega")
draws.Sigma <- fit$draws("Sigma")
summary(draws.Omega)
summary(draws.Sigma)
```

`Omega` is the correlation matrix (`Sigma` the covariance matrix) for the vector of random effects for subject `i`, `alpha[i,]`. In this case, with four outcomes `alpha[i, 1:3]` are random intercepts for outcome 1 to 3; and `alpha[i,4:7]` are random slopes for outcomes 1 to 4. The model has a hard sum-to-zero constraint for the random intercepts (to help with the identifiability of the latent time parameter and convergence), so the fourth random intercept is defined to be minus the sum of the first 3 random intercepts.
 
`Omega[2,1]` then is the correlation between the random intercepts for outcomes 1 and 2; and `Omega[4,1]` is the correlation between random intercept and slope for outcome 1; and so on.

**Comment by mitezo** [comment]
Thank you very much for your detailed response. Your answers have been incredibly helpful.

**Comment by mitezo** [comment]
Thank you very much for your detailed response. Your answers have been incredibly helpful.

**Comment by mitezo** [comment]
Thank you very much for your detailed response. Your answers have been incredibly helpful.
